#!/usr/bin/env python3
"""gen_xtensa_stubs.py — extract the ESP32-S3 flasher-stub configs + blobs from
the OpenOCD-esp32 source into a Python data module (espjtag/xtensa_stubs.py).

FAITHFUL, MECHANICAL transcription — NOT hand-typed, NOT reverse-engineered. The
structure is declared in OpenOCD's source (contrib/.../esp32s3/stub_image.h: the
per-command #defines + the .inc code/data blobs, matching struct
esp_flasher_stub_config in src/flash/nor/esp_flash.h). We just parse those and
emit them verbatim, so espjtag loads the SAME prebuilt stub OpenOCD does (#29).

Source pinned at the espjtag upstream.lock SHA (== current master). Re-run after
bumping the pin. Usage:
    python3 scripts/gen_xtensa_stubs.py [path-to-openocd-esp32]
"""
import os
import re
import sys

OOCD_DEFAULT = "/mnt/2tb/git_mirror/espressif/openocd-esp32"
# chips we extract (just S3 for #29; the list makes adding S2/others mechanical)
CHIPS = {"esp32s3": "S3"}
# the struct esp_flasher_stub_config fields that are simple scalars (from #defines)
SCALAR_FIELDS = [
    "entry_addr", "bss_sz", "apptrace_ctrl_addr", "log_buff_addr", "log_buff_size",
    "trap_record_addr", "trap_entry_addr", "iram_org", "iram_len", "dram_org",
    "dram_len",
]
# map struct field -> the #define suffix used in stub_image.h
DEFINE_SUFFIX = {
    "entry_addr": "ENTRY_ADDR", "bss_sz": "BSS_SIZE",
    "apptrace_ctrl_addr": "APPTRACE_CTRL_ADDR", "log_buff_addr": "LOG_ADDR",
    "log_buff_size": "LOG_SIZE", "trap_record_addr": "TRAP_RECORD_ADDR",
    "trap_entry_addr": "TRAP_ENTRY_ADDR", "iram_org": "IRAM_ORG",
    "iram_len": "IRAM_LEN", "dram_org": "DRAM_ORG", "dram_len": "DRAM_LEN",
}


def read_inc_blob(path):
    """An OpenOCD .inc is bin2char output: lines of 0xNN,0xNN,... — return bytes."""
    out = bytearray()
    with open(path) as f:
        for line in f:
            for tok in re.findall(r"0x([0-9a-fA-F]{2})", line):
                out.append(int(tok, 16))
    return bytes(out)


def parse_chip(oocd, chip):
    """Parse one chip's stub_image.h -> {cmd_name: {field: value/bytes}}."""
    base = os.path.join(oocd, "contrib/loaders/flash/espressif/images", chip)
    hdr = os.path.join(base, "stub_image.h")
    text = open(hdr).read()
    # all #define ESP_STUB_CMD_<NAME>_<SUFFIX> <hexval>
    defines = dict(re.findall(
        r"#define\s+(ESP_STUB_CMD_\w+)\s+(0x[0-9a-fA-F]+|\d+)", text))
    stack = int(re.search(r"#define\s+ESP_STUB_STACK_SIZE\s+(\d+)", text).group(1))
    cmds = {}
    # each config block: .name = "cmd_xxx", ... — find the cmd token from the cfg name
    for m in re.finditer(r"\.name\s*=\s*\"(cmd_\w+)\"", text):
        name = m.group(1)
        up = name.upper()                                  # cmd_flash_write -> CMD_FLASH_WRITE
        prefix = "ESP_STUB_" + up                          # ESP_STUB_CMD_FLASH_WRITE
        cfg = {"stack_default_sz": stack}
        ok = True
        for field in SCALAR_FIELDS:
            key = f"{prefix}_{DEFINE_SUFFIX[field]}"
            if key not in defines:
                ok = False
                break
            cfg[field] = int(defines[key], 0)
        if not ok:
            continue                                       # a cmd without full defines (skip)
        code = read_inc_blob(os.path.join(base, f"stub_{name}_code.inc"))
        data = read_inc_blob(os.path.join(base, f"stub_{name}_data.inc"))
        cfg["code"] = code
        cfg["data"] = data
        cmds[name] = cfg
    return cmds


def emit(all_chips, tramp_win, out_path, oocd_sha):
    lines = [
        '"""xtensa_stubs.py — GENERATED by scripts/gen_xtensa_stubs.py. DO NOT EDIT.',
        "",
        "ESP32-S3 flasher-stub configs + code/data blobs, transcribed VERBATIM from",
        "OpenOCD-esp32 contrib/loaders/flash/espressif/images/<chip>/stub_image.h so",
        "espjtag loads the SAME prebuilt stub OpenOCD does (#29). Fields mirror",
        "struct esp_flasher_stub_config (src/flash/nor/esp_flash.h).",
        "",
        f"Source: espressif/openocd-esp32 @ {oocd_sha}",
        '"""',
        "",
        "# {chip: {cmd_name: {field: value, 'code': bytes, 'data': bytes}}}",
        "STUBS = {",
    ]
    for chip, cmds in all_chips.items():
        lines.append(f"    {chip!r}: {{")
        for name, cfg in sorted(cmds.items()):
            lines.append(f"        {name!r}: {{")
            for field in SCALAR_FIELDS + ["stack_default_sz"]:
                lines.append(f"            {field!r}: {hex(cfg[field])},")
            lines.append(f"            'code': bytes.fromhex({cfg['code'].hex()!r}),")
            lines.append(f"            'data': bytes.fromhex({cfg['data'].hex()!r}),")
            lines.append("        },")
        lines.append("    },")
    lines.append("}")
    lines.append("")
    # The windowed trampoline (esp_xtensa_stub_tramp_win.S): expects a0=0, a1=sp,
    # a8=entry, a2..a6=args; sets up the callx8 frame, forwards args a2..a6->
    # a10..a14, does native `callx8 a8` so the windowed stub ENTRY/RETW run
    # correctly, result in a2. Loaded right after the code section.
    lines.append(f"TRAMP_WIN = bytes.fromhex({tramp_win.hex()!r})")
    lines.append("")
    open(out_path, "w").write("\n".join(lines))


def main():
    oocd = sys.argv[1] if len(sys.argv) > 1 else OOCD_DEFAULT
    if not os.path.isdir(oocd):
        sys.exit(f"openocd-esp32 source not found at {oocd}")
    sha = os.popen(f"git -C {oocd} rev-parse --short HEAD").read().strip() or "?"
    all_chips = {}
    for chip in CHIPS:
        cmds = parse_chip(oocd, chip)
        all_chips[chip] = cmds
        print(f"{chip}: {len(cmds)} stub configs "
              f"({', '.join(sorted(cmds))[:80]}...)")
    tramp_win = read_inc_blob(os.path.join(
        oocd, "contrib/loaders/trampoline/espressif/xtensa",
        "esp_xtensa_stub_tramp_win.inc"))
    print(f"tramp_win: {len(tramp_win)} bytes")
    root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    out = os.path.join(root, "espjtag", "xtensa_stubs.py")
    emit(all_chips, tramp_win, out, sha)
    sz = os.path.getsize(out)
    print(f"-> {out} ({sz:,} bytes)")


if __name__ == "__main__":
    main()
